= Point and Extent

== Overview

The `point` gives a position in the 2D cartesian coordinate space. The
`extent` is the same pair of numbers used to mean a size rather than a
position, and is a specialization of `point` with the movement members
removed.

== point

The point indicates position in the 2D cartesian coordinate space,
represented by the `x` and `y` coordinates:

=== Declaration

[source,c++]
----
struct point
{
               point();
               point(float x, float y);
               point(point const&) = default;
   point&      operator=(point const &) = default;

   bool        operator==(point const& other) const;
   bool        operator!=(point const& other) const;

   point       move(float dx, float dy) const;
   point       move_to(float x, float y) const;
   point       reflect(point p) const;

   float       x;
   float       y;
};
----

=== Expressions

==== Notation

[cols="1,3"]
|===
| `x`, `y` | Scalar coordinates.
| `dx`, `dy` | Relative scalar coordinates.
| `p`, `p2` | Instance of `point`
|===

==== Constructors and assignment

[source,c++]
----
// Default constructor [1].
point{}

// Constructor [2].
point{ x, y }

// Copy constructor. [3]
point{ p }

// Assignment [4]
p = p2
----

==== Semantics

. Default construct a `point` with initial values `{ 0, 0 }`
. Construct a `point` given initial values `x`, and `y`.
. Copy construct a `point `, `p`.
. Assign `p2`, to `p`.

==== Equality

[source,c++]
----
// Equality [1]
p == p2

// Non-equality [2]
p != p2
----

==== Semantics

. Returns `true` if `p2`, is equal to `p`.
. Returns `true` if `p2`, is not equal to `p`.

==== Transformation

[source,c++]
----
// Move [1]
p.move(dx, dy)

// Move To [2]
p.move_to(x, y)

// Reflection [3]
p.reflect(p2)
----

==== Semantics

. Move `p` `dx` and `dy` distance relative to `p`. Non-mutating. Returns the
  moved instance of `point`.
. Move `p` to absolute coordinates `x` and `y`. Non-mutating. Returns the
  moved instance of `point`.
. Reflect a `point`, `p`, at 180 degree rotation of point, `point`.
  Non-mutating. Returns the reflected instance of `point`.

==== Member access

[source,c++]
----
p.x
p.y
----

==== Semantics

. Direct access to members `x` and `y`.

== extent

The `extent` struct is a specialization of `point` but deletes the members
`move`, `move_to`, and `reflect`. `extent` is intended for specifying
2-dimensional sizes.

=== Declaration

[source,c++]
----
struct extent : point
{
   using point::point;

               extent(point p);

   point       move(float dx, float dy) const = delete;
   point       move_to(float x, float y) const = delete;
   point       reflect(point p) const = delete;
};
----
