= Resources

== Overview

Artist finds fonts and images by searching a list of directories. These
are the calls that manage that list and search it.

== resources

Resources (e.g. images) that are identified by file names can be absolute or
relative paths. For relative paths, a vector of paths is searched, in the
order they appear in the vector. Platform code provides the initial paths as
appropriate. Applications may add additional paths as needed, using the
add_search_path function. search_first=true puts the path at the top of the
vector and will be searched first.

[source,c++]
----
void        add_search_path(fs::path const& path, bool search_first = false);
fs::path    find_file(fs::path const& file);
fs::path    app_data_path();
----

=== Expressions

[source,c++]
----

// Add a search path [1]
add_search_path(path)
add_search_path(path, true)

// Search for a file [2]
find_file(path)
----

=== Notation

[cols="1,3"]
|===
| `path` | Instance of `std::filesystem::path`
|===

=== Semantics

. Add a directory search path. This path, and all paths added via
  `add_search_path`,  will be used when searching for a resource file. The
  second variant, with the second argument, specifies if the directory
  search path will be pushed into the end (default `false`) or pushed to the
  front (second argument is `true`) of the list. If `true`, the directory
  search path will be searched first.
. Find a resource file by searching the list of directory search paths.
  Returns an empty path if file is not found. returns an instance of
  `std::filesystem::path`.
